### ISSUE TITLE
springboot2.6+版本

### ISSUE THREAD

**Issue by chenfeiwu** [lkqm/spring-api-versioning#4]
2.6以上的版本如何适配

**Comment by lkqm** [comment]
2.6版本是会报错吗？

**Comment by wei63w** [comment]
我换了好几个版本 都报错
`org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.wyc.Application]; nested exception is java.lang.IllegalStateException: Failed to introspect annotated methods on class com.github.lkqm.spring.api.version.ApiVersionAutoConfiguration
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:610) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:311) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:250) ~[spring-context-5.3.18.jar:5.3.18]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:207) ~[spring-context-5.3.18.jar:5.3.18]
	a`

**Comment by lkqm** [comment]
明天测试修复下，发个版

**Comment by lkqm** [comment]
已经修复支持 spring-boot 2.6.x, 2.7.x , 请使用1.4.0版本，注意中央仓库同步有延迟，后续可以拉到包

**Comment by Vhibli** [comment]
我下载了源码后也解决了，本来想来反馈下的。感谢作者
